version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "io.papermc.paper:paper-api"
        versions: ["1.21.x"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
