# yaml-language-server: \$schema=https://www.schemastore.org/bukkit-plugin.json
name: 1vs1
version: "${version}"
main: net.ninebolt.onevsone.OneVsOnePlugin
api-version: "${apiVersion}"

permissions:
  1vs1.admin:
    description: Administrative 1vs1 commands
    default: op
