# yaml-language-server: \$schema=https://www.schemastore.org/bukkit-plugin.json
name: 1vs1
version: "${version}"
main: net.ninebolt.onevsone.OneVsOnePlugin
api-version: "${apiVersion}"

commands:
  1vs1:
    description: 1vs1 arena command
