# yaml-language-server: \$schema=https://www.schemastore.org/bukkit-plugin.json
name: ketto
version: "${version}"
main: net.ninebolt.ketto.KettoPlugin
api-version: "${apiVersion}"

permissions:
  ketto.admin:
    description: Administrative ketto commands
    default: op
